In [2]:
import numpy as np

In [3]:
a=np.array([5,7,8])
a

array([5, 7, 8])

In [4]:
a.shape

(3,)

In [5]:
b=np.array([[1,2,3],[3,4,5]])
b

array([[1, 2, 3],
       [3, 4, 5]])

In [6]:
b.shape

(2, 3)

In [7]:
c=np.array([[[1,2,3],[1,2,3],[43,65,65]]])
c

array([[[ 1,  2,  3],
        [ 1,  2,  3],
        [43, 65, 65]]])

In [8]:
c.shape

(1, 3, 3)

In [9]:
k=np.array([[3,8,4],
            [9,3,5],
            [11,15,17],
            [19,31,8]])
k.shape

(4, 3)

In [10]:
#subscripting
print(k[1,0])
k[2,:3] #or k[2]

k[:,1:2]

9


array([[ 8],
       [ 3],
       [15],
       [31]])

In [11]:
k1=np.array([[[4,41],[8,81],[7,71]],
             [[3,31],[1,11],[5,51]],
             [[6,61],[9,91],[13,131]]])
print(k1)
k1.shape

[[[  4  41]
  [  8  81]
  [  7  71]]

 [[  3  31]
  [  1  11]
  [  5  51]]

 [[  6  61]
  [  9  91]
  [ 13 131]]]


(3, 3, 2)

In [12]:
k1[2:3,1:3,:2]

array([[[  9,  91],
        [ 13, 131]]])

In [13]:
b[1,:3]=[12,42,54]
b


array([[ 1,  2,  3],
       [12, 42, 54]])

In [14]:
b[:,1]=[1,2]
b

array([[ 1,  1,  3],
       [12,  2, 54]])

In [15]:
b +3

array([[ 4,  4,  6],
       [15,  5, 57]])

In [16]:
b[2:,:,]=[1,1,1]

In [17]:
np.append(b,[[1],[1]],axis=1)

array([[ 1,  1,  3,  1],
       [12,  2, 54,  1]])

In [18]:
np.delete(b,1,axis=0)

array([[1, 1, 3]])