In [1]:
import numpy as np 

In [2]:
np.arange(1,11,1)
#allow floating numbers to to be incremented 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
list(range(1,11,1))
#does not allow

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [14]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [10]:
np.ones([4,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
np.zeros([4,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
p=np.ones((3,4))
p

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
p.astype(int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [21]:
p8=p.astype('uint8')
p8

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=uint8)

In [22]:
#uint8,16,32,64
#int 8,........
#float8........


In [23]:
np.random.randint(1,100,5)

array([41, 32, 82, 26, 86])

In [24]:
np.random.randint(1,100,[4,5])

array([[85, 11, 92, 41, 82],
       [ 3, 55,  6, 51, 15],
       [69, 97, 42, 21, 45],
       [68, 55,  1, 93, 57]])

In [29]:
np.random.seed(1000)
np.random.randint(1,100,[3,5])                     

array([[52, 88, 72, 65, 95],
       [93,  2, 62,  1, 90],
       [46, 41, 93, 92, 37]])

In [30]:
np.random.rand(3,2) 

array([[0.8517472 , 0.57432043],
       [0.77250273, 0.9066506 ],
       [0.06032431, 0.02119571]])

In [31]:
np.random.randn(3,4)

array([[ 0.75215791, -1.21184194,  1.34554282, -0.0996391 ],
       [ 0.41326545, -1.52099316,  0.21154853,  0.19237876],
       [ 0.11911147, -0.63762903, -0.40062252,  0.45535403]])

In [36]:
np.loadtxt('data.txt',dtype='str')

array([['this', 'is', 'a', 'new', 'file'],
       ['here', 'we', 'get', 'some', 'data']], dtype='<U4')

In [39]:
np.loadtxt('data1.txt',delimiter=',')

array([[45., 32., 12., 54., 32.],
       [12., 53., 68.,  4.,  6.],
       [12., 46., 80., 35., 65.]])

In [41]:
a=np.random.randint(10,1000,[3,6])
a

array([[133, 449, 610, 466, 412,  12],
       [855, 709, 563, 656, 148, 244],
       [685, 829, 512, 447,  57, 578]])

In [43]:
np.savetxt('data3.txt',a,delimiter='|',fmt='%d')

In [44]:
a.sum()

8365

In [46]:
a.sum(axis=1)#the axis value becomes 1 for rows and vice versa


array([2082, 3175, 3108])

In [48]:
a.mean(axis=1)

array([347.        , 529.16666667, 518.        ])

In [49]:
a.max(axis=1)

array([610, 855, 829])

In [50]:
a.argmax(axis=1)

array([2, 0, 1], dtype=int64)

In [51]:
a.flatten()


array([133, 449, 610, 466, 412,  12, 855, 709, 563, 656, 148, 244, 685,
       829, 512, 447,  57, 578])